name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1

      - name: Check if tests exist
        id: check-tests
        run: |
          if find . -name "*_test.go" | grep -q .; then
            echo "::set-output name=tests_exist::true"
          else
            echo "::set-output name=tests_exist::false"
          fi

      - name: Run tests
        if: steps.check-tests.outputs.tests_exist == 'true'
        run: go test ./...

      - name: Create PR
        if: steps.check-tests.outputs.tests_exist == 'true' && success()
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ github.ref }}"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Automated PR: All tests passed"
          pr_body: "This is an automated Pull Request. All tests passed, so it's ready for review."